name = "ErgodicControlPlots"
uuid = "76340805-c5be-40dd-9397-3f5a12ecf927"
authors = ["Joshua Ott <joshuaott2@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
